# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/inelos/projects/oop-python/src_07/ui/lab_7.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 598)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(520, 40, 241, 131))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 190, 241, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_a = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.line_a.setFrame(True)
        self.line_a.setAccelerated(False)
        self.line_a.setMaximum(1000)
        self.line_a.setObjectName("line_a")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_a)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.line_b = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.line_b.setMaximum(1000)
        self.line_b.setObjectName("line_b")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_b)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_c = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.line_c.setEnabled(False)
        self.line_c.setMaximum(1000)
        self.line_c.setObjectName("line_c")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_c)
        self.info = QtWidgets.QLabel(Form)
        self.info.setGeometry(QtCore.QRect(10, 529, 501, 61))
        self.info.setText("")
        self.info.setObjectName("info")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 340, 241, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 221, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.regular = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.regular.setChecked(True)
        self.regular.setObjectName("regular")
        self.verticalLayout_2.addWidget(self.regular)
        self.random = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.random.setEnabled(True)
        self.random.setObjectName("random")
        self.verticalLayout_2.addWidget(self.random)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dense_x = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.dense_x.setMinimum(1)
        self.dense_x.setMaximum(100)
        self.dense_x.setOrientation(QtCore.Qt.Horizontal)
        self.dense_x.setObjectName("dense_x")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dense_x)
        self.dense_y = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.dense_y.setMinimum(1)
        self.dense_y.setMaximum(100)
        self.dense_y.setOrientation(QtCore.Qt.Horizontal)
        self.dense_y.setObjectName("dense_y")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dense_y)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.balance = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.balance.setObjectName("balance")
        self.verticalLayout_2.addWidget(self.balance)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(540, 520, 201, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.generate_new = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.generate_new.setEnabled(False)
        self.generate_new.setObjectName("generate_new")
        self.verticalLayout_3.addWidget(self.generate_new)
        self.clean = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.clean.setObjectName("clean")
        self.verticalLayout_3.addWidget(self.clean)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Лабораторная работа №7"))
        self.groupBox.setTitle(_translate("Form", "Вид фигуры:"))
        self.radioButton.setText(_translate("Form", "Прямоугольник"))
        self.radioButton_2.setText(_translate("Form", "Квадрат"))
        self.radioButton_3.setText(_translate("Form", "Круг"))
        self.radioButton_4.setText(_translate("Form", "Эллипс"))
        self.groupBox_2.setTitle(_translate("Form", "Параметры:"))
        self.label.setText(_translate("Form", "Сторона \'a\'"))
        self.label_2.setText(_translate("Form", "Сторона \'b\'"))
        self.label_3.setText(_translate("Form", "Радиус"))
        self.groupBox_3.setTitle(_translate("Form", "Способ подсчёта:"))
        self.regular.setText(_translate("Form", "Регулярный"))
        self.random.setText(_translate("Form", "Случайный"))
        self.label_4.setText(_translate("Form", "Плотность X"))
        self.label_5.setText(_translate("Form", "Плотность Y"))
        self.balance.setText(_translate("Form", "Уравнять плотности"))
        self.generate_new.setText(_translate("Form", "Сгенерировать сетку заново"))
        self.clean.setText(_translate("Form", "Очистить"))


