# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/inelos/projects/oop-python/src_cw/ui/cw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(771, 490)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 80, 251, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.stockmans = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.stockmans.setMinimum(1)
        self.stockmans.setMaximum(10)
        self.stockmans.setProperty("value", 2)
        self.stockmans.setObjectName("stockmans")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stockmans)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.time_of_work = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.time_of_work.setMinimum(1)
        self.time_of_work.setProperty("value", 10)
        self.time_of_work.setObjectName("time_of_work")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.time_of_work)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.queue_length = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.queue_length.setMinimum(1)
        self.queue_length.setProperty("value", 3)
        self.queue_length.setObjectName("queue_length")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.queue_length)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.speed_of_service = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.speed_of_service.setMinimum(1)
        self.speed_of_service.setMaximum(10)
        self.speed_of_service.setProperty("value", 3)
        self.speed_of_service.setObjectName("speed_of_service")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.speed_of_service)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.workers = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.workers.setMinimum(1)
        self.workers.setMaximum(15)
        self.workers.setProperty("value", 5)
        self.workers.setObjectName("workers")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.workers)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 80, 471, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.queue_bar = QtWidgets.QProgressBar(self.formLayoutWidget_2)
        self.queue_bar.setProperty("value", 0)
        self.queue_bar.setObjectName("queue_bar")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.queue_bar)
        self.workers_bar = QtWidgets.QProgressBar(self.formLayoutWidget_2)
        self.workers_bar.setProperty("value", 0)
        self.workers_bar.setTextVisible(True)
        self.workers_bar.setObjectName("workers_bar")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.workers_bar)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 731, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.addr = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.addr.setObjectName("addr")
        self.horizontalLayout_2.addWidget(self.addr)
        self.port = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.port.setObjectName("port")
        self.horizontalLayout_2.addWidget(self.port)
        self.connect = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.connect.setObjectName("connect")
        self.horizontalLayout_2.addWidget(self.connect)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(40, 260, 691, 191))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(350, 180, 309, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.update_settings = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.update_settings.setObjectName("update_settings")
        self.verticalLayout.addWidget(self.update_settings)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.info = QtWidgets.QLabel(Form)
        self.info.setGeometry(QtCore.QRect(20, 460, 731, 21))
        self.info.setText("")
        self.info.setObjectName("info")
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(280, 150, 471, 21))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.time_scale = QtWidgets.QSlider(self.formLayoutWidget_3)
        self.time_scale.setMinimum(-1)
        self.time_scale.setMaximum(10)
        self.time_scale.setTracking(True)
        self.time_scale.setOrientation(QtCore.Qt.Horizontal)
        self.time_scale.setInvertedAppearance(False)
        self.time_scale.setInvertedControls(False)
        self.time_scale.setObjectName("time_scale")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.time_scale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Курсовая работа"))
        self.label_2.setText(_translate("Form", "Время износа инструмента"))
        self.label_3.setText(_translate("Form", "Длина очереди"))
        self.label_4.setText(_translate("Form", "Время обслуживания"))
        self.label_5.setText(_translate("Form", "Количество рабочих"))
        self.label.setText(_translate("Form", "Количество кладовщиков"))
        self.label_6.setText(_translate("Form", "Заполненность очереди:"))
        self.label_7.setText(_translate("Form", "Ожидающие рабочие"))
        self.label_8.setText(_translate("Form", "Адрес, порт:"))
        self.addr.setPlaceholderText(_translate("Form", "127.0.0.1"))
        self.port.setPlaceholderText(_translate("Form", "5555"))
        self.connect.setText(_translate("Form", "Подключение"))
        self.update_settings.setText(_translate("Form", "Обновить настройки"))
        self.stop.setText(_translate("Form", "Stop"))
        self.start.setText(_translate("Form", "Start"))
        self.label_9.setText(_translate("Form", "Масштаб времени"))


